version: "3.8"

services:
  # User Service
  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "5001:5000" # 
    environment:
      - MONGO_URI=mongodb://mongo:27017/userdb
      - PORT=5000
    depends_on:
      - mongo

  # MongoDB Server
  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo_data:
